### ISSUE TITLE
Google Analyticsの追加

### ISSUE THREAD

**Issue by dc7290** [dc7290/d-suke-notebook-blog#1]
# Google Analyticsの追加
パフォーマンスに影響を与えないようにGAを追加する。

**Comment by dc7290** [comment]
vercelのanalyticsを使うことで解決

**Comment by d-chiba-q** [comment]
vercelのanalyticsで計測するのはパフォーマンスだったため、やはりgoogle analyticsをいれる

**Comment by dc7290** [comment]
vercelのanalyticsはパフォーマンスを計測するものだったため、やはりgoogle analyticsを入れる

**Comment by dc7290** [comment]
Duplicate of #18 
設定ずみ
